services:
  client:
    build:
      dockerfile: Dockerfile dev
      context: .
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    ports:
      - '9000:3000'
    environment:
      - WDS_SOCKET_PORT=0