version: "3"
services:
  client:
    image: "rustolebayev/multi-client"
    hostname: client
  server:
    image: "rustolebayev/multi-server"
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_USER=$PG_USER
      - PG_HOST=$PG_HOST
      - PG_DB=$PG_DB
      - PG_PASSWORD=$PG_PASSWORD
      - PG_PORT=$PG_PORT
  worker:
    image: "rustolebayev/multi-worker"
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "rustolebayev/multi-nginx"
    hostname: nginx
    ports:
      - "80:80"