services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: redis:4
  nginx:
    depends_on:
      - api
      - client
    ports:
      - 3050:80
    restart: always
    build:
      dockerfile: Dockerfile dev
      context: ./nginx
  api:
    restart: always
    depends_on:
      - postgres
      - redis
    build:
      dockerfile: Dockerfile dev
      context: ./server
    volumes:
      - /home/node/app/node_modules
      - ./server:/home/node/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DB=postgres
      - PG_PASSWORD=postgres_password
      - PG_PORT=5432
  client:
    restart: always
    build:
      dockerfile: Dockerfile dev
      context: ./client
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app
    environment:
      - WDS_SOCKET_PORT=0
  worker:
    restart: always
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile dev
      context: ./worker
    volumes:
      - /home/node/app/node_modules
      - ./worker:/home/node/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
