name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t rustolebayev/react-test -f ./client/"Dockerfile dev" ./client
      - run: docker run -e CI=true rustolebayev/react-test npm test

      - run: docker build -t rustolebayev/multi-client ./client
      - run: docker build -t rustolebayev/multi-nginx ./nginx
      - run: docker build -t rustolebayev/multi-server ./server
      - run: docker build -t rustolebayev/multi-worker ./worker

      - run: docker push rustolebayev/multi-client
      - run: docker push rustolebayev/multi-nginx
      - run: docker push rustolebayev/multi-server
      - run: docker push rustolebayev/multi-worker
